name: Deb package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: sudo apt install libusb-1.0-0-dev

    - name: Generate deb
      run: make deb

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.0.0
      with:
        path: "*.deb"
